### PR TITLE
Testing BW and more

### PR DESCRIPTION
**Pull request by nantonel**
Re-written many functions using in-place versions, changed names of parameters, added new tests including to Baum Welch. Should take into account most of the issues of #1. Benchmarks not updated yet.

### CODE REVIEW

**Comment by junekiwi** [comment]
Thanks for the PR! Give me a few days to review the changes :-)  
Changing the fields and functions names is a big changes but yours are indeed more consistent. Since we're still at an early stage this may be doable :-)

**Comment by nantonel** [comment]
yes, that's what I had in my mind when I've made these mods! 😃

**Comment by junekiwi** [comment]
The tests fails on my installation with `Distributions` v0.16.4:
```
suffstats is not implemented for (DiscreteNonParametric{Int64,Float64,Base.OneTo{Int64},Array{Float64,1}}, Array{Int64,1}, Array{Float64,1})
suffstats is not implemented for (Gamma{Float64}, Array{Float64,1}, Array{Float64,1})
```

However they pass with the latest version v0.20.0. Can you add the following in `Project.toml`:
```
[compat]
Distributions = ">= 0.20.0"
```

Thanks!

**Comment by nantonel** [comment]
should be fixed now! 😉

**Comment by junekiwi** [comment]
Hi, I'm a bit busy for the moment but I haven't forgotten you :-)

**Comment by junekiwi** [comment]
I've rebased your changes in the `refactor_v1` branch where I'll prepare the release of the v1.0.  
I want to make a few cosmetic changes to the code before merging to master.

**Comment by junekiwi** [comment]
Hi, I finally released the new version of the library, including the renaming of the HMM fields.

I did not merged all of your changes as-is, as I wanted to preserve some of the original design decisions (`AbstractHMM` types parameters, for example), and the PR was quite big with _intertwined_ commits.

I mentioned you where I thought it was appropriate (release notes, `messages.jl` and `viterbi.jl` files).

Thanks for your improvements, your implementations were much cleaner and faster :-)

**Comment by nantonel** [comment]
That's great! Thank you! 😄

**Pull request merged**
